url: "https://www.alltechnotricks.com"
baseurl: "/"
exclude: [node_modules, README.md]
plugins:
- jekyll-sitemap
compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []
